### PR TITLE
Fixing 508 contrast issues and empty link issues

### PR DESCRIPTION
**Pull request by KimberlyMunoz**
This changes the default values for some of the colors to resolve any WCAG testing issues and fixes a blank link for accessibility reasons.
## Review
- @jimmynotjim 
- @Scotchester 
- Award Winning @contolini 
## Notes

I've changed the values, but pa11y is still finding a contrast error that WAVE, tota11y and node-wcag cannot find. If you find it, let me know! Run `npm install` and `npm test` and let me know what your result is.

### CODE REVIEW

**Comment by contolini** [comment]
@KimberlyMunoz Try removing the `-r ci` from the test script to get better output from pa11y: https://github.com/cfpb/cf-typography/blob/gh-pages/package.json#L4.

The old version of pa11y exited 0 even if it failed so a separate CI runner had to be used. That is no longer the case.

**Comment by contolini** [comment]
Oh and upgrade pa11y: `npm i pa11y@latest --save`

**Comment by KimberlyMunoz** [comment]
Here's the results. The contrast issue is the one that is failing.

```
 > WCAG2AA.Principle2.Guideline2_4.2_4_2.H25.2
   Check that the title element describes the document.
 > WCAG2AA.Principle2.Guideline2_4.2_4_4.H77,H78,H79,H80,H81 (37 occurences)
   Check that the link text combined with programmatically determined link context identifies the purpose of the link.
 > WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Abs
   This element is absolutely positioned and the background color can not be determined. Ensure the contrast ratio between the text and all covered parts of the background are at least 4.5:1.
 > WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
   This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 2.21:1. Recommendation: change text colour to #757575.
 > WCAG2AA.Principle1.Guideline1_3.1_3_1_A.G141
   The heading structure is not logically nested. This h2 element appears to be the primary document heading, so should be an h1 element.
 > WCAG2AA.Principle1.Guideline1_3.1_3_1.H48 (2 occurences)
   If this element contains a navigation section, it is recommended that it be marked up as a list.
 > WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.A.Placeholder (13 occurences)
   Anchor element found with link content, but no href, ID or name attribute has been supplied.
```

**Comment by contolini** [comment]
Oh and upgrade pa11y: `npm i pa11y@latest --save`

**Comment by KimberlyMunoz** [comment]
Found the issue that pa11y is still erroring on. It's a screenreader only span. 

```
 • Error: This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 2.21:1. Recommendation: change text colour to #757575.
   ├── WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail
   ├── #category-slug > div > div > a > span:nth-child(2)
   └── <span class="u-visually-hidden">Category:</span>
```

**Comment by Scotchester** [comment]
@KimberlyMunoz Is it the `.u-visually-hidden` class that's giving it the color that causes that result?

**Comment by KimberlyMunoz** [comment]
Mm-hmm. Although when I inspect, it [doesn't look like the color should create a contrast ratio problem](http://webaim.org/resources/contrastchecker/?fcolor=5B3B63&bcolor=ffffff), unless it was on a black background.

I'm tempted to remove this from the demo for now to make the tests pass because this really isn't an accessibility issue. The contrast will be seen by no one.

**Comment by Scotchester** [comment]
Ok, but will the use of `.u-visually-hidden` in any project trigger the same failure? If so, we need to figure out how to fix that.

**Comment by jimmynotjim** [comment]
Does it pass if you get rid of the 1px height and width?

**Comment by KimberlyMunoz** [comment]
> Does it pass if you get rid of the 1px height and width?

But that'd modifying the actual `.u-visually-hidden` class to get a bad test to pass. I'm okay removing it from the documentation, since our documentation is already a little terrible, but I think the solution is either getting pa11y to fix the issue or switching to node-wcag.

**Comment by jimmynotjim** [comment]
I'm just curious if that's where the issue is, rather than the color contrasts.

**Comment by KimberlyMunoz** [comment]
If that's the case, I'm going to advocate even stronger for scrapping pa11y since the error says `This element has insufficient contrast at this conformance level.` I'll get to it tomorrow. I want to start a little bit of v1 work today.

**Comment by Scotchester** [comment]
I don't suppose there's a way to get it to tell you the background color it's checking against? My assumption would have been that it would walk up the DOM until it found an ancestor with a non-transparent background color, but if that were true, it'd be checking against white.

I thought node-wcag used pa11y? Isn't node-wcag what's running these tests?

**Comment by contolini** [comment]
@Scotchester Nah, pa11y is powered by [HTML CodeSniffer](http://squizlabs.github.io/HTML_CodeSniffer/). node-wcag is powered by [AChecker](http://achecker.ca/).

**Comment by Scotchester** [comment]
TIL:

> all the cf-components use pa11y because node-wcag wasn't ready yet

@contolini says he will review the open issues on node-wcag soon and let us know if it's ready for us to start transitioning to it.

**Comment by KimberlyMunoz** [comment]
Cool. 🐧 I removed the screenreader tag that was causing problems, so I'll add that back in. Is this PR on hold until Chris finishes the node-wcag issues, or are there other things holding it back from being merged?

**Comment by Scotchester** [comment]
That's a good question… I mean, the point of this PR is to fix failing tests, so I guess if a test is still going to be failing, I'd rather wait until we can swap it out with node-wcag.

**Comment by jimmynotjim** [comment]
@contolini What's the timeline for node-wcag being usable here? If it's going to be more than 2 weeks, lets merge this as is so it doesn't go stale and we can benefit from the fixes that it does address. We can then add an issue for outstanding requests and reference node-wcag as a blocker to that issue.

**Comment by KimberlyMunoz** [comment]
Going to close this issue. I'm going to be changing color vars and I don't want this to be merged after that one. The accessibility issues will just have to stay broken.

**Pull request closed without merging**
