### PR TITLE
Font size vars

### PR DESCRIPTION
**Pull request by jimmynotjim**
Updated mixins to use localized var for easy adjustments and expose `@font-size` var when the mixin is used. The exposed var saves you from having to manually write media-queries for text-size changes.
## Additions
- `@font-size` vars
## Removals
- None
## Changes
- Updated a MQ to use the variable
## Testing
- open `/docs/index.html` and view changed mixins, should be the same
## Review
- @cfarm 
- @Scotchester 
- @ascott1 
## Checklist
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
- [x] Passes all existing automated tests
- [x] New functions include new tests
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged
- [x] Visually tested in supported browsers and devices 
- [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
## Notes
- Not sure why but even without any source changes Grunt was producing diff files, so I committed those first for easier review.
- See https://github.com/cfpb/cf-forms/pull/38#discussion_r41342216 and https://github.com/cfpb/cf-core/pull/50

### CODE REVIEW

**Comment by cfarm** [comment]
:+1: lookin good

**Comment by Scotchester** [comment]
Needs version bump and change log entry.

**Comment by Scotchester** [comment]
Also has merge conflicts.

**Comment by jimmynotjim** [comment]
@Scotchester Fixed conflicts and version bumped. Will tag and release after merging.

**Comment by Scotchester** [comment]
:+1:

**Pull request merged**
