### PR TITLE
Restore borders on .block-link pattern

### PR DESCRIPTION
**Pull request by Scotchester**
It seems that in the mad dash to set up reusable variables throughout our
components, the borders were inadvertently turned white on the
`.block-link` pattern. This fixes that.
### Before

screen shot 2015-04-01 at 18 28 25
### After

screen shot 2015-04-01 at 18 28 59
## Please review:
- @himedlooff
- @jimmynotjim / @anselmbradford / @sebworks

### CODE REVIEW

**Comment by Scotchester** [comment]
Extra ping for @himedlooff because I'm not sure if he got notified when I edited the OP to correct my misspelling of his handle.

**Comment by jimmynotjim** [comment]
Looks good. What's up with the updates to cf-icons? Did grunt pull in an updated version while running?

**Comment by Scotchester** [comment]
Yeah, just a typical dependency update (for the purposes of the docs). I suppose I should mention that in the change log. Hadn't even realized it happened.

**Comment by himedlooff** [comment]
looks good to me

**Comment by Scotchester** [comment]
Thanks! :shipit:

**Pull request merged**
