### PR TITLE
Fixes #28 - adds list__links

### LINKED ISSUE #28: Add .list__links pattern
It seems that `.list__links` was accidentally omitted from #25.

### PR DESCRIPTION
**Pull request by anselmbradford**
Fixes #28 - adds `list_links` pattern. Both the default and the icon list variant.
## Additions
- Adds list__links pattern.
- Adds EOF newline.
## Removals
- Removes excess whitespace.
## Changes
- Re-generates docs.
## Testing
- Visit `/demo/index.html`
## Review
- @Scotchester 
- @virginiacc 
## Preview

Large screen size:
screen shot 2015-03-19 at 6 01 14 pm

Mobile screen size:
screen shot 2015-03-19 at 6 01 29 pm
## Notes
- I'm not sure how to test this on Blackberry? I can't use Ghostlab to access my localhost.

### CODE REVIEW

**Comment by anselmbradford** [comment]
## Browsers
- [x] Chrome
- [x] Safari
- [ ] FF
- [ ] IE10
- [ ] IE9
- [ ] IE8
- [ ] IE7
- [x] Opera
- [x] iOS7.1
- [ ] Android 4
- [ ] Blackberry Bold

## Accessibility
- [x] Keyboard friendly - _tested keyboard in Chrome_
- [ ] Screen reader friendly

## Other
- [ ] Is useable without CSS
- [ ] Is useable without JS
- [x] Flexible from small to large screens - _has breakpoint and changes spacing on small screens_
- [x] ~~No linting errors or warnings~~ _N.A. no linting task in Gruntfile_
- [x] ~~JavaScript tests are passing~~ _N.A. no testing task in Gruntfile_

**Comment by Scotchester** [comment]
:+1:

As this is just a transfer of stuff from cfgov-refresh to cf-typography, I wouldn't worry too much about finishing the checklist. But you can if you want.

**Comment by jimmynotjim** [comment]
:+1:

**Comment by anselmbradford** [comment]
> As this is just a transfer of stuff from cfgov-refresh to cf-typography, I wouldn't worry too much about finishing the checklist. But you can if you want.

@Scotchester Okay in that case, I'll touch on it more rigorously in https://github.com/cfpb/cf-typography/issues/29 since that re-works the ones with icons. Merge and tag away! Actually, on that note, do I need to update the Changelog as part of this PR?

**Comment by Scotchester** [comment]
Yes, please do update the change log, and the version number in `bower.json`.

**Comment by anselmbradford** [comment]
@Scotchester Would you consider this a minor or patch version?

**Comment by Scotchester** [comment]
I'd say minor, since it adds new functionality.

**Comment by anselmbradford** [comment]
@Scotchester Updated in https://github.com/anselmbradford/cf-typography/commit/aab448bffaab7073963d2621fcec62fc5967faf0

**Comment by Scotchester** [comment]
:+1:

**Comment by Scotchester** [comment]
Please tag the release.

**Pull request merged**
